### PR TITLE
Make library work with Immutable.js stores

### PR DESCRIPTION
**Pull request by okjulian**

### CODE REVIEW

**Comment by jevakallio** [comment]
Thanks for this @JulianMayorga! 🍺  

I'll have to test this a bit and check that everything is working smoothly. Will get back to this next week.

**Comment by okjulian** [comment]
Thank you @jevakallio  for such a useful library. The documentation was super useful to me.

Let me know if anything comes up after your tests!

**Comment by unindented** [comment]
I'd be against landing this PR. `redux-persist-immutable` is **huge** because of `transit-immutable-js` and `transit-js`. It will make your library too big to ship in a browser scenario.

You can already use Immutable.js by passing the necessary `persistOptions`, and you don't force people who don't care about `transit-js` to include it in their bundles and serve it to their users.

**Comment by migueloller** [comment]
@JulianMayorga, try to rebase master? Having the merge commit in the PR makes it very hard to identify the _new_ changes you made (as opposed to all changes that have happened in the project since you forked it, which seems to be quite a bit ago). Also, there are various merge conflicts due to this.

**Comment by okjulian** [comment]
Sorry @migueloller! I made some changes to my fork of redux-offline, but I never intended those changes to be accepted by you.

I made them knowing that they won't be compatible with v2 of redux-offline. For example, I reverted my fork to use v1 installation method, and I also unignored lib folder because I did not want to publish my fork.

I think this means that I should close this PR to avoid future confusion. So feel free to close this :D

I would be more than willing to help you guys if you ever want to support immutable states! So please tell me if you want to reopen a discussion regarding Immutable.

Cheers!

**Comment by migueloller** [comment]
It's up to @jevakallio what happens but he's likely open to adding these features. It's just that it's a bit hard to look at the changes without rebasing master.

**Comment by okjulian** [comment]
I think it's better if we start an issue about using Immutable stores, so I created it on #78. Let's continue the discussion over there!

@jevakallio, I am closing this old PR to avoid confusion.

**Comment by fabriziomoscon** [comment]
I created a PR #99 for this very same issue

**Pull request closed without merging**
