### PR TITLE
replace RN AsyncStorage with community package

### PR DESCRIPTION
**Pull request by usrbowe**
Fixes https://github.com/redux-offline/redux-offline/issues/349

Replace deprecated 'react-native' AsyncStorage module with community package. 

> For RN60+

### CODE REVIEW

**Comment by calumpeak** [comment]
@usrbowe thanks for this - Im not massively familiar with RN so thank you for bringing this to our attention. These kinds of issues are something we want to me more pluggable/easily fixable with V3.

**Review by calumpeak — APPROVED** [review]

**Comment by calumpeak** [comment]
@sorodrigo when you get a chance 👍

**Comment by sorodrigo** [comment]
I removed the `@react-native-community/async-storage` because it's an optional dependency that should be installed externally, same as `NetInfo` and `react-native`.

**Comment by sorodrigo** [comment]
Also I changed the tag so it's not constantly changing, now the Native tag is `native`. Before it was `native.0` apologies.

**Pull request merged**
