### PR TITLE
React Native 0.60.x compatiblity

### PR DESCRIPTION
**Pull request by ryanlntn**
Use @react-native-community/netinfo for react native 0.60.x compatibility. This is a breaking change for react native < 0.60.x users.

### CODE REVIEW

**Comment by adbs1** [comment]
I think this needs prioritising. It has been suggested that a DIY implementation of detectNetwork can be used as a workaround, I don't believe that would work as the default detectNetwork is loaded before the DIY implementation and the references to an incompatible reactNative version throws errors (will gladly be proven wrong.)

**Comment by sorodrigo** [comment]
Thanks I have a look at it. There's been talk about preparing for v3. Maybe what we can do is create an alternative tag where this fix lands and where we can start working on v3.

@calumpeak

**Comment by calumpeak** [comment]
@sorodrigo We definitely need to tag this differently to break any older versions of react native. Going forward, we should try to avoid environment deps in the application as much as possible. 
I don't think cutting for V3 here works too well, though it is a breaking change. An alternative tag is the right way to go and make sure it's highlighted on the readme. It may just be a case of making sure users have the right deps in their package json though. Thoughts?

**Comment by sorodrigo** [comment]
ok any preferred name for the tag?

**Comment by calumpeak** [comment]
Maybe `-native` or something?

**Comment by Gringox** [comment]
Team, do you have a release date for a version of redux-offline that includes this changes? @sorodrigo @calumpeak

**Comment by sorodrigo** [comment]
Fix available at https://www.npmjs.com/package/@redux-offline/redux-offline/v/2.5.2-native.0

**Pull request merged**
