### PR TITLE
Ability to configure what happens when there are no retries left (rather than simply discarding)

### PR DESCRIPTION
**Pull request by bradstiff**
**This feature should have no effect to existing applications**

Added `config.discardOnRetryCountExceeded`, which defaults to true. Requests are discarded when there are no retries left (current behavior).

Setting the flag to false causes the request to remain in the outbox rather than be discarded. This is useful for applications that cannot afford to lose any requests due to network errors.

Added a `retryCountExceeded` flag to OfflineState to provide visibility to when the above occurs.

Added an `OFFLINE_RESET_RETRY_COUNT` action to enable resetting the retry state of the request, causing redux-offline to start over with retrying the request according to the configured decay schedule.

Updated docs.

Added some tests. I was not able to run the tests in __tests__/index.js, including an integration test that I added there.  I was getting the below error. Any idea why?

TypeError: Cannot read property 'origin' of undefined
    at Window.get localStorage [as localStorage] (C:\Users\Brad\source\repos\redux-offline\node_modules\jsdom\lib\jsdom\browser\Window.js:256:26)
    at _hasStorage (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\defaults\asyncLocalStorage.js:89:101)
    at hasLocalStorage (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\defaults\asyncLocalStorage.js:107:10)
    at getStorage (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\defaults\asyncLocalStorage.js:116:12)
    at Object.<anonymous>.exports.default (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\defaults\asyncLocalStorage.js:8:17)
    at getStoredState (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\getStoredState.js:18:67)
    at Immediate.<anonymous> (C:\Users\Brad\source\repos\redux-offline\node_modules\redux-persist\lib\persistStore.js:43:36)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

### CODE REVIEW

**Comment by sorodrigo** [comment]
Thank for contributing! I have some questions. Mainly I want to understand the use case to see if this can be handled in userland with custom discard/retry. Could you give an example of how you use this?

**Comment by bradstiff** [comment]
I am writing an app where the user will be recording data and sending it to an API periodically, in the background. The user will be in the field while recording, and connectivity will be intermittent. While recording, it is not important that the user know if the data has been received by the API or not. But the unreceived data cannot be discarded. 

The user will eventually save the entire activity, including any unsaved data. The user needs immediate confirmation that everything was saved, or an error message with the chance to retry. Eventual consistency is not an option.

But now it occurs to me that I could simply setup an infinite retry, e.g., every five minutes, for the data. And when the user saves the activity, if the OfflineState indicates retryScheduled, dispatch an OFFLINE_COMPLETE_RETRY action to immediately restart the queue. And then handle whatever happens next via error messaging.

I will try that to see if it meets my needs.

**Comment by sorodrigo** [comment]
> I am writing an app where the user will be recording data and sending it to an API periodically, in the background. The user will be in the field while recording, and connectivity will be intermittent. While recording, it is not important that the user know if the data has been received by the API or not. But the unreceived data cannot be discarded.
> 
> The user will eventually save the entire activity, including any unsaved data. The user needs immediate confirmation that everything was saved, or an error message with the chance to retry. Eventual consistency is not an option.
> 
> But now it occurs to me that I could simply setup an infinite retry, e.g., every five minutes, for the data. And when the user saves the activity, if the OfflineState indicates retryScheduled, dispatch an OFFLINE_COMPLETE_RETRY action to immediately restart the queue. And then handle whatever happens next via error messaging.
> 
> I will try that to see if it meets my needs.

Thanks, I hate to stonewall a feature request when it's already implemented. But if something is achievable with the existing API is better from a maintainability standpoint.

Also another solution is to add the data that's being saved as a meta in the rollback action. Then if an action is discarded you get to store that in some sort of cache. And when the user has connection you can re-map the cached data to offline requests. Or you could even have a sync button to do this manually. This would also be more transparent to the user:

10 requests made -> 6 failed  -> 2 retrying -> 4 stored for later retry.

**Comment by HuYuee** [comment]
@sorodrigo hi, We need a synchronized button to reopen the request in the offline queue. Can you provide an example? thx very much

**Comment by sorodrigo** [comment]
@HuYuee sorry for replying so late. Did you find a way to solve your issue?

**Pull request closed without merging**
