### PR TITLE
Add a guide to config redux-offline to use redux-persist v5

### PR DESCRIPTION
**Pull request by jarvisluong**
Add section for helping to use custom redux-persist version

Related issue: https://github.com/redux-offline/redux-offline/issues/119

### CODE REVIEW

**Review by calumpeak — APPROVED** [review]

**Comment by sorodrigo** [comment]
I wonder if it's worth including that guide directly into our docs?

**Comment by calumpeak** [comment]
@sorodrigo perhaps as I'd imagine there's a few that want to. Out of curiosity, what's the reason that we haven't bumped the version internally?

**Comment by sorodrigo** [comment]
That would mean a breaking change, and I think both @wacii and I wanted to do that eventually. Life has gotten in the way of me dedicating serious time to this project. I really appreciate all that you're doing.

The main issues for not upgrading are that:
- v5 doesn't support top level immutable state.
- v5 doesn't support HMR

We recently had a discussion about how ImmutableJS is slowly being replaced by Immer in the community, and that maybe supporting top level immutable state wasn't a top priority anymore. I still have to think how/if we need to implement immutability for the next version using immer.
Loosing HMR is a pain, because it's such a nice feature, maybe we can help redux-persist with that, maybe we're screwed and it's a tradeoff. I would need time to do some research. Honestly, I've been on the brink of a burnout at work, so haven't paid as much attention to R-O as it deserves.

**Comment by sorodrigo** [comment]
I really enjoy working on this project, but I feel like sometimes I might be a bottleneck and I shouldn't be. It would be great if we could have a video call someday and meet also with @wacii and try to organise our efforts better. Currently I'm the only one that can push to npm, this probably shouldn't be the case.

**Comment by calumpeak** [comment]
Sounds like decent concerns tbh. Definitely a major version change would be needed to get this in, alongside sorting out the reducers etc.
We should sort a call out/slack group or something of the like just to open out comms. I only get sporadic bursts of productivity outside of work also so I do some work on this (like the tools) when I have a free evening and not exhausted.

**Pull request merged**
