### PR TITLE
Feature cancel offline specific action

### PR DESCRIPTION
**Pull request by maraujop**
Hi there,

We've found redux-offline to be a great bundle of offline paradigms handling. However we have come across a use case not currently solved. Sometimes the use may do an action and want to cancel that action while being online.

For example maybe he sent 3 or 4 emails, but wants one to be cancelled before syncing with connection.

This way the use can dispatch a `DEQUEUE_ACTION` passing:

```
      dispatch({
        type: DEQUEUE_ACTION,
        payload: {
          type: 'CANCEL_EMAIL',
          payload: {
            emailId,
          },
        },
      })
```

If you consider merging this PR, I can refactor it and add docs & tests.

Thanks, cheers
Miguel

### CODE REVIEW

**Comment by sorodrigo** [comment]
Hey! Thanks a lot, we recently merged a PR that will allow the user to override the `enqueue` and `dequeue` methods. I think that with this, you can build a custom enqueue method that dequeues other actions.

**Comment by dabit1** [comment]
Hi guys, I think that `enqueue` doesn't fix it at all. I mean, if you want to cancel some enqueued action you will need to dispatch another action that has offline meta data. 
Imagine a TODO list:

1. I'm offline and I add a TODO
2. The action is enqueued.
3. I still being offline and I remove the TODO

The action to remove the TODO know that this TODO was not sent to the server, then it will need to remove the adding action from the outbox, otherwise although the TODO was removed it will be sent to the server. A solution could be to dispatch an action with `meta.offline` properties and add a custom property to dequeue the old action.
However, if the action was registered (via `registerAction`) it will be retried although it had been removed from the outbox, I'm right?

**Comment by sorodrigo** [comment]
I think we need to think about `registerAction` and how to deal with this. There's a PR from @wacii that makes `offlineActionTracker` completely optional so maybe this will help, or we may need to make some changes, I haven't been able to check it out.

About `enqueue` not fixing it, I think the queue config provides all needed to implement this. You can decide to remove an action from the outbox when enqueueing. I think this is what you're suggesting.

If you're interested in this behaviour, you should check out this. https://github.com/redux-offline/queue/tree/master/smart-queue

@prsn has started working on it but maybe you could help him.

**Comment by wacii** [comment]
@sorodrigo It sounds like they want to remove actions on an arbitrary action, not when enqueueing a new offline action. In which case `enqueue` doesn't help.

@dabit1 Removing from the outbox will prevent an action from being retried. Although you should only do this if that action is not being currently processed because of how `dequeue` works currently (you could end up dropping an additional action).

`registerAction` is for the returned promise. Technically you should let the `offlineActionTracker` know if you are abandoning an action, but nothing's going to break if you don't. Other than the very small memory leak of the numerical id saved in the tracker.

**Comment by dabit1** [comment]
@sorodrigo: @wacii is right, I want to remove actions from outbox without enqueueing a new offline action.

@wacii  if the action is being currently processed what exactly I have to do? I think should be a documented way to do that. If you guys can't I will study how it library works and I will try to fix it.

**Comment by piranna** [comment]
> I want to remove actions from outbox without enqueueing a new offline action.

I think this is the correct concept of cancelling an action, enqueueing it would be to revert it instead.


> if the action is being currently processed what exactly I have to do?

In that case then it has already been send and could be considered that's already done, so only possible thing is to wait until we get the response: if it fails and get back to the queue then remove it (cancel it), if it success then send inmediatly a new action to revert it before processing any others.

**Comment by sorodrigo** [comment]
> so only possible thing is to wait until we get the response: if it fails and get back to the queue then remove it (cancel it), if it success then send inmediatly a new action to revert it before processing any others.

I think this will add a lot of complexity, I would consider all actions in process as sent. And when it fails like you said, you could remove it. But I’m not sure is worth handling the cases where the action being processed succeeds.

@dabit1 ok I now understand your use case. For me makes more sense adding a DELETE offline action, and dequeueing both the DELETE and the CREATE when non have been sent, makes things more predictable and avoids the edge cases mentioned before. But that said, is just my way of seeing this and I don’t see why not allow both use cases 🙂.

**Comment by piranna** [comment]
> I would consider all actions in process as sent

This has a problem we are not considering: if an action behaviour depend on a previous one and this got removed, what happens? Should devs wait until they get a confirmation that previous operation was successful so both local and remote state is stable?


> And when it fails like you said, you could remove it. But I’m not sure is worth handling the cases where the action being processed succeeds.

In a first iteration could be enough to remove the action when it fails as if nothing happened, but it would be good later to also consider the case if it succed by allowing to set the request that needs to be done to revert the action, the same way it's defined the commit and rollback actions.

**Comment by sorodrigo** [comment]
> if an action behaviour depend on a previous one and this got removed, what happens?

This is getting way to complicated, I think it's not our responsibility. If user cancels an action, he should be aware of the consequences. I don't want to add all this complexity. Thoughts?

**Comment by wacii** [comment]
@dabit1 I wouldn't bother handling when the action is currently being processed. But I imagine it could be done with a reducer to handle the three cases (the currently processed action results in a schedule retry, commit or rollback) and a middleware to swallow the schedule retry action.

This seems brittle to me though. @sorodrigo's suggestion is better imo.

@sorodrigo I think the library already has too much configuration, especially considering how simple it is. If we wanted to make the library more flexible, I think it should be done with better architecture, not an ever expanding config object. So no, I wouldn't want to add this.

**Comment by sorodrigo** [comment]
I agree, the feature requested can be achieved with the current queue config. Maybe it can't be achieved without dispatching a second offline action but I don't think that's a bad thing.

**Comment by piranna** [comment]
> I imagine it could be done with a reducer to handle the three cases (the currently processed action results in a schedule retry, commit or rollback) and a middleware to swallow the schedule retry action.

It would be good to have that module in the org, seems somewhat easy to do and would left core untouched...

**Pull request closed without merging**
