### PR TITLE
fix typings for Config’s offlineActionTracker callbacks

### PR DESCRIPTION
**Pull request by alexlhoffman**

### CODE REVIEW

**Comment by calumpeak** [comment]
Duplicate of #243 ?

**Comment by alexlhoffman** [comment]
At a glance, yes it appears so, the only purpose of this is to fix the typings for offlineActionTracker in Config. My apologies.

**Comment by calumpeak** [comment]
@alexlhoffman No Worries
@sorodrigo I'm actually up for keeping this PR over #243. Commit History/Message is cleaner/informative.

**Review by calumpeak — APPROVED** [review]

**Comment by sorodrigo** [comment]
Sounds good!

**Pull request merged**
