### PR TITLE
Allow queue to be configured

### PR DESCRIPTION
**Pull request by wacii**
Customize queue behavior by specifying `config.queue.peek()`, `config.queue.enqueue()`, and `config.queue.dequeue()`.

### CODE REVIEW

**Comment by sorodrigo** [comment]
Hey @wacii , did you have time tonplay more with this? Do you think we should include it soonish? If you think its ready I’ll make time to test and merge.

**Comment by wacii** [comment]
@sorodrigo I'll review this again tomorrow, but I remember it being a fairly simple change that addressed a few things people have been asking for.

**Comment by wacii** [comment]
Rebased against develop. I think this is fine to include. Just a few minor changes to get this to work.

The diff for _src/send.js_ looks a little busy, but only because I had to indent the reducer. The actual changes to the reducer are that I am binding `queue.enqueue` and `queue.dequeue` from the config to `offlineUpdater` instances, and that I moved the code that was in the `enqueue` and `dequeue` functions of _src/send.js_ back into the reducer. Otherwise we would have two different enqueue functions, and that would be confusing.

**Comment by sorodrigo** [comment]
Really liking this feature! 🎉  🎉

**Comment by flipace** [comment]
This is exactly what I need right now - any idea when a new redux-offline version will be published with this?

**Pull request merged**
