### PR TITLE
Add prettier as eslint plugin

### PR DESCRIPTION
**Pull request by wacii**
Compares prettier output to actual code when `yarn lint` is run, reporting the differences as errors. `yarn prettier` applies the changes using the `--fix` flag.

### CODE REVIEW

**Comment by wacii** [comment]
See #22.

**Comment by sorodrigo** [comment]
Awesome!! Thanks for all the help. Do you have a twitter account or email I can reach you at? Seems like something broke when I merged the other PR, and now travis is complaining. Could you take a look a it so we can merge this? Thanks again, amazing job!

**Comment by sorodrigo** [comment]
Another thing, I accidentally merged last PR into master. I'm trying to enforce git flow, I'm not reverting last PR, its too much hassle, but for the next PRs could you point them at the develop branch please.  🙏

**Comment by wacii** [comment]
Oh right, I didn't really notice the develop branch, sorry about that. I'll direct my PRs there from now on.

You can reach me at wacii@mail.com. I do not twitter.

I'll take a look at the error now.

**Comment by wacii** [comment]
Just needed to apply prettier to PR#23 as any differences register as lint errors now.

**Pull request merged**
