### PR TITLE
Add the current action to peek

### PR DESCRIPTION
**Pull request by Xyzor**
Since we have the wonderful option to handle the queue, I don't see why couldn't we see the action, that runs through the offline middleware, while we peek.

## Personal reason:

In my current project I had to store every offline action that discarded and had an *invalid error response.

>*invalid: In this case, every response thats status is lower than 400 and higher than 499

Because I wanted to store them in their original place `outbox`, I had to know what is the current action that is going through the middleware, so I could return the right next action.

```javascript
/**
* The actual code, that I'm using to return the next action in peek()
*/
const nextAction = null;
for (let i = 0; i< outbox.length; i++) {
 const offlineAction = outbox[i];
  if (
    // A boolean value, that I add to the meta, to mark the preservable actions 
    !offlineAction.meta.preserve
    // The reason for the action parameter. Return the current actions equivalent part from the outbox
    || action.type === offlineAction.type
    // If there are more discarded action in the outbox, call the next one, if this one succeeded
    || action.type === offlineAction.meta.offline.commit.type
  ) {
    nextAction = offlineAction;
    break;
}
return nextAction;

### CODE REVIEW

**Comment by sorodrigo** [comment]
Hello thanks for contributing, we’re talking about adding another param named context that will include both the current action and the offline state.

**Comment by Xyzor** [comment]
It's good to know. If I'm correct, this pr can be closed then.

**Comment by sorodrigo** [comment]
Well if you’d like to help us we could use your PR with some additions.

The next thing we need to know is what to put inside `context`. Thoughts @wacii?

**Comment by Xyzor** [comment]
Well, I sent in the pr, so you just have to accept it :wink:.

**Comment by sorodrigo** [comment]
Ok but we need to make the changes before merging.

**Comment by wacii** [comment]
@sorodrigo The current action and offline state seems reasonable. So...

```js
const context = { action, offline };
peek(array, context)
```

@Xyzor We're sticking everything in an object called `context` just in case someone thinks of something else that's needed (we already have someone who needs the online status). This way we can add things without breaking people's code.

**Comment by sorodrigo** [comment]
Sounds great!

@Xyzor We'll need the context object in all queue methods.

**Comment by Xyzor** [comment]
I created a new PR, with the requested changes: #217.

**Pull request closed without merging**
