### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by sorodrigo**
This PR will updates eslint, flow, babel, etc.

After updating flow and eslint some new flow errors came to light...

**TODO:** fix flow

OH! And drops `react` as a dev dependency, that's been there since forever!

### CODE REVIEW

**Review by calumpeak — APPROVED** [review]

**Comment by calumpeak** [comment]
Question - is it worth having all of redux offline in a monorepo? I can see a lot of shared dependencies between this and tools (e.g. default configs, typings etc)

**Review by calumpeak — COMMENTED** [review]
CI no likey :(

**Comment by sorodrigo** [comment]
@echoes221 yep it's still `wip` will fix during this week. I think yes it would make sense, but don't really feel like messing with all that now 😂 . Eventually we'll need to do it, don't know if for v3? @wacii

**Comment by wacii** [comment]
@sorodrigo Not sure what to do with v3. Solving the multiple tab issue would require a lot of new code, doesn't play particularly well with redux, and would be useless for native. I think v3 might just be upgrading Redux Persist and dropping support for immutable root state. And I have mixed feelings about that.

So I wouldn't worry about v3 for this. The changes look good though. I'll review once the tests pass and whatnot.

**Comment by sorodrigo** [comment]
Hello I just re-read your last comment about v3. I wonder if supporting immutable is still a priority, the community seems to be moving on to use @mweststrate's [Immer](https://github.com/mweststrate/immer) that provides immutability without forcing you to use non js objects everywhere. Redux itself is building a new starter kit that recommends the use of `Immer` so **TLDR** I'm not so sure anymore...

**Comment by sorodrigo** [comment]
@echoes221 @wacii 
This is ready to be reviewed, I changed some stuff in the `updater.js` and `send.js` files in order to make flow work, I also bumped babel to 7 as it's no longer a beta. Tests are passing 🎉 .
If you agree with this we should **Squash and merge** 😄

**Review by calumpeak — APPROVED** [review]

**Pull request merged**
