### PR TITLE
Fix previously deprecated methods have been removed in NetInfo

### PR DESCRIPTION
**Pull request by hqdai**
Fix Previously deprecated methods have been removed in NetInfo

### CODE REVIEW

**Comment by tiagosatur** [comment]
Guys, please merge this PR!

**Comment by calumpeak** [comment]
@hqdai I'm assuming this is with the `NetInfo` community package bump to v5.0?

@sorodrigo Should we be specifying a peer dependency?

@tiagosatur Working on it, but we have to check a few things first - we were unaware that NetInfo was getting bumped, please use V4 for the time being (which is still stable).

**Comment by hqdai** [comment]
> @hqdai I'm assuming this is with the `NetInfo` community package bump to v5.0?
> 
> @sorodrigo Should we be specifying a peer dependency?
> 
> @tiagosatur Working on it, but we have to check a few things first - we were unaware that NetInfo was getting bumped, please use V4 for the time being (which is still stable).

hi @calumpeak,
fetch() function is available on both V4 and V5, but on V5 they remove deprecated functions completely, I did the test on both V4 and V5 of NetInfo, they work fine.
Check out this link for CHANGE LOG from NetInfo: https://github.com/react-native-community/react-native-netinfo/blob/master/CHANGELOG.md

**Comment by tiagosatur** [comment]
@calumpeak I already updated RN to v 0.61.2. But ios is giving me netinfo deprecated error because of redux-offline, I cant go back. So, I changed the package to the version @redux-offline/redux-offline@native.0 but it does not update the online reducer. I appreciate your help

**Comment by calumpeak** [comment]
#373

**Comment by hqdai** [comment]
@calumpeak, 
Thank you for merging, please consider to update npm :D

**Comment by roiecoh** [comment]
I'm having trouble with aws-appsync package which is dependent on redux-offline on RN 0.61.5.
I've downloaded the source and ran babel compilation after the latest merge but now getting
TypeError: Object is not a constructor (eveluating 'new_state2.default(_configuration)')
I'm using "@react-native-community/netinfo": "^4.6.1"

Any help is appreciated
Thanks

**Comment by zyasir** [comment]
Thank you very much for this fix, is npm updated with it?

**Comment by stanwolverine** [comment]
Still getting "Invariant Violation: NetInfo has been removed from React Native" error.

**Comment by simonmitchell** [comment]
@stanwolverine did you manage to work out which version of this package we need to use to get around that "Invariant Violation" issue? Or other steps we need to take?

**Comment by stanwolverine** [comment]
@simonmitchell Yes. Use "2.5.2-native.3" version of "@redux-offline/redux-offline" and latest version of "@react-native-community/netinfo"

**Comment by simonmitchell** [comment]
Thanks! That helped 😄

**Comment by bekicelmir** [comment]
Re: issue

We;re still experiencing same issues with with @redux-offline/refux-offline: 2.5.20-native.3 and "@react-native-community/netinfo": 5.5.0.
RN 0.61.5.

Tried downgrading netinfo but encountered same issues. Downgrading netinfo to 4..5.0 and redux-offline to 2.5.2-native.1, we got rid of errors.

Anyone with some info on this? Bug still presented on latest version ?

**Comment by stanwolverine** [comment]
Our app is working great on latest versions

**Pull request merged**
