### PR TITLE
Able to dispatch a thunk after commit or rollback

### PR DESCRIPTION
**Pull request by dabit1**
Sometimes we need to dispatch an action after another action is dispatched. We can use redux-thunk for this purpose. But currently redux-offline cannot store thunks because redux store cannot store pure functions. This is the reason why I created this middleware. We cannot persist a pure function but we can persist the name of the function and its params, that is the key. I hope you find my solution good.

Regards,

David Escalera

### CODE REVIEW

**Comment by sorodrigo** [comment]
Hey! Thanks for contributing, funny enough I used an almost identical solution here #177.

**Comment by dabit1** [comment]
@sorodrigo  may be my solution is simpler. What do you think?

**Comment by sorodrigo** [comment]
Hey! So as promised, let's resume this discussion. I think that what @wacii mentioned in my approach is still valid in yours:

> If you are willing to link the offline actions with the ~observers~ thunks outside of the actions themselves, you could implement this as a separate library. Or use one of the existing solutions, like redux saga.
> I think doing it that way would be somewhat preferable, as it would allow new versions of an app to better use persisted actions. If you linked actions and ~observers~ thunks at startup rather than at action creation, you could link an old action with a new ~observer~ thunk when you update your app, rather than be stuck with an old action and an old ~observer~ thunk...if that makes any sense.

Basically, if we setup the thunks in the action meta, we can't really migrate them if needed.

Originally I had introduced this feature in the `redux-offline` core, but have since reevaluated my decision. I prefer your approach of using it as an external library.
I would create it under `@redux-offline`, but outside of the core package.

**Comment by dabit1** [comment]
Yeah let's do it. I agree to create it under @redux-offline but outside of
the core package. It would be the best aproach.

**Comment by ForumT** [comment]
Hey,

Any progress on this one? Badly need this feature!

**Comment by sorodrigo** [comment]
@ForumT hey, this will take some time to go out. We have another repo that holds a plugin yet to be published. And I was thinking on hosting all non core stuff in there.

Which means setting up the monorepo probably with lerna), adding the middleware, making some changes (mentioned in my last comment) and releasing.

Sorry 😐. Another solution for this is to use `redux-saga`.

**Comment by piranna** [comment]
Have been this published in an external repo yet? Does anyone has an example about how to use sagas with `redux-offline`?

**Comment by ForumT** [comment]
@piranna: https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/redux-saga.md. You can check this. Rest all is same.

**Comment by piranna** [comment]
> @piranna: https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/redux-saga.md. You can check this. Rest all is same.
> 
> Merge state
>  Show all checks

Thank you! :-D

**Comment by calumpeak** [comment]
Second to @sorodrigo's suggestion of `redux-saga` I'd also highly recommend `redux-observable` for some reactive goodness. I've been using offline and observable together to do some really powerful things in other applications.

**Comment by sorodrigo** [comment]
Hello there! So sorry for the delay, I created this: https://github.com/redux-offline/tools .

Could you create a new PR there so we include it with your commits, @dabit1 ?

**Comment by piranna** [comment]
We are having problems using this middleware, since it's not run on the commit or rollback actions. Debugging it we have found that when dispatching the initial action it's done with the middleware as the `dispatch()` function (probably due to how redux `composeEnhancers()` and `applyMiddleware()` function works), but when the commit action is dispatched, it's done using directly the store `dispatch()` method, so no middleware is being executed at all.

We are not fully sure if it's a fault on our side regarding redux-offline configuration, or a but in redux-offline itself... Our store configuration is like this:

```js
import { applyMiddleware, compose, createStore } from 'redux'

import reduxOfflineThunkMiddleware from './thunk-middleware'
import rootReducer from '../../reducers'

import { createUser } from '../../actions/user'

const initialState = {}

const windowCompose = (typeof window !== 'undefined') && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
const composeEnhancers = windowCompose || compose

const store = createStore(
  rootReducer,
  initialState,
  composeEnhancers(
    applyMiddleware(reduxOfflineThunkMiddleware({ createUser })),
    offline()
  )
)
```

**Comment by sorodrigo** [comment]
@piranna So this issue seems similar to the problem we had with `createOffline`. The solution was as simple as changing the order in which we compose the enhancers. Maybe you should try the `createOffline` approach. Follow the [sagas](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/redux-saga.md) guide and I bet it'll work.

**Comment by sorodrigo** [comment]
@dabit1 hey I know it's a hassle to create yet another PR so, if you want I can copy your code to the new repo. Just let me know it's ok, I don't feel comfortable doing it without your approval.

**Pull request closed without merging**
