### PR TITLE
[WIP] Add initial jest setup and initial tests

### PR DESCRIPTION
**Pull request by fossage**
* Add /src/__tests__ directory

* Add Jest and other testing related dev dependencies

* Add jest-setup.js file at project root

* Add tests for middleware, createOfflineStore, config, and batch

I've only got tests in for config, createOfflineStore, middleware, and batch so far, but before I went too much further I wanted to get some feedback and see if heading in the right direction so far.  A few items that I currently have questions about are:

- I am currently putting the `__tests__` directory within the `src` directory. Does that work, or would you rather it be at the root of the project?

- I'm using the convention of mirroring the `src` directory structure within the `__tests__` directory, i.e. the test for `src/defaults/batch.js` is at `__tests__/defaults/batch.test.js`.  The idea behind this being that it makes it easy to know where to look to find a corresponding test for something, but I'm open to any suggestions on the ideal directory structure.

- I've put the `jest-setup.js` file at the root of the project.  Although it's not technically a config file, I tend to think of it like a config file because it is setting up some globals for the Jest environment, so I typically put it at the root of the project, however I think inside of the `__tests__` directory would also be a fine place for it.

Other than that, any feedback on the tests themselves would be great. They're all pretty straight forward unit tests at this point, but if we get these ones to a point where you feel like we're ready to move forward, then I'll finish off the rest of the unit tests and work towards getting some larger integration tests in.

### CODE REVIEW

**Comment by jevakallio** [comment]
@fossage thank you so much for this! 🎉 I will test these tests (heh), review the correct intent and land these soon.

**Comment by jevakallio** [comment]
@fossage I just noticed the WIP tag. 

I was going to rebase this on the latest master (some of the jest configurations have already been introduced to master by https://github.com/jevakallio/redux-offline/pull/33) but if you intend to continue working on this, I think it's best you do the rebase as part of your workflow so that I don't mess up your history :)

**Comment by fossage** [comment]
@jevakallio , oh yea no problem.  I realized after I submitted the PR that most other PR's were being submitted against master, so I'll get these moved over re-submit.  I think I'll have to update some of the existing tests anyway, so I'll hopefully be able to bang that out tonight.  

In terms of branching strategy, is develop just being used for local development and all changes intended for remote should be on master?

**Comment by jevakallio** [comment]
@fossage the develop branch is deprecated and I will remove it now. All changes should be targeted to master.

Thank you so much for your help on this! Please be aware that I just landed some large changes in [1.1.0](https://github.com/jevakallio/redux-offline/releases/tag/v1.1.0) and [2.0.0](https://github.com/jevakallio/redux-offline/releases/tag/v2.0.0) - see the release notes for summaries. 

Sorry to be a moving target - I won't make any more large changes until we can land these tests :)

**Comment by jevakallio** [comment]
@fossage this PR was automatically closed when I deleted develop. Please open a new one against master!

**Pull request closed without merging**
