### PR TITLE
Add an action to reset the state

### PR DESCRIPTION
**Pull request by dabit1**
For example, when you do a logout in your app you need to reset the whole offline state.

### CODE REVIEW

**Comment by sorodrigo** [comment]
👏🏻👏🏻👏🏻

**Comment by Timer** [comment]
Wouldn't this be better handled in your application? I'm not sure how this is a concern of the `redux-offline` library.

**Comment by sorodrigo** [comment]
@Timer I think that there should be a way to clean the outbox, it shouldn't be used in the internals of redux-offline but just as an API for users to handle from the outside.

**Comment by sorodrigo** [comment]
Merging this to my fork. Cheers!

**Pull request merged**
