### PR TITLE
[Default effector] Automatically `JSON.stringify()` body object

### PR DESCRIPTION
**Pull request by piranna**
This fixes issue #35

### CODE REVIEW

**Comment by sorodrigo** [comment]
Thanks! We should definitely include this. I'm thinking, this would be a breaking change to some people using the previous default effect. We should take that into account when making the next release. Maybe hold it off until we have substantial changes?

What do you think @wacii ?

**Comment by wacii** [comment]
This sounds like a reasonable convenience. Technically I think you can provide the JSON wrapped in a Blob, but I can't think of why anyone would do this. So it's probably safe to include now as it doesn't matter if the user has already serialized their object (`JSON.stringify(someStr) === someStr`).

Still, there's no reason to rush the change, so I'm fine playing it safe and waiting for a future release.

**Comment by piranna** [comment]
> I'm thinking, this would be a breaking change to some people using the previous default effect.

Absolutely. I would like to hve it ASAP... but I know that's breaking the current API, being it on purpose or an undercover bug if everybody have been using custom effectors (I think the latest). I think I can live with some hacks by the moment :-)

By the way, there's no tests for effectors, we should add them... I find [coveralls](https://coveralls.io/) to be a nice service, I can be able to add support for it in another pull-request if you want :-)


> So it's probably safe to include now as it doesn't matter if the user has already serialized their object (JSON.stringify(someStr) === someStr).

Unluckily this check would fail always, since it will always add quotes chars since strings are a valid JSON value. Only check here is to check if input value is a string and use `JSON.parse()` on it, and if it doesn't throw an exception, then it's a JSON stringfied object, and if so, then it's an object that can be stringified. I can be able to add this backwards compatibility check with a big deprecation TODO note on this pull-request if you want...

**Comment by sebasgarcep** [comment]
Hey @piranna! Do you think it may be possible for you to provide a test case on this?

@wacii, fetch seems to take several different data types (Blobs, Typed Arrays, etc.) in the body. Are you completely sure stringifying those data types won't affect the payload, headers, etc?

**Comment by piranna** [comment]
> Hey @piranna! Do you think it may be possible for you to provide a test case on this?

I think I can get some time to add them. Do you want them on this pull-request or a new one? Do I add also the backward compatibility check? This way we can have all it integrated and ready to merge and publish it on master...

**Comment by sebasgarcep** [comment]
@piranna  The tests should be on this pull request. You should mock fetch, otherwise the tests may fail. I think it can be done like this:

```javascript
global.fetch = jest.fn();
```
Anyways, thanks for your work and swift response. :)

**Comment by piranna** [comment]
> global.fetch = jest.fn();

I'll try to do that.


> Anyways, thanks for your work and swift response. :)

Well, I'm always connected, so... :-P Anyway, what timezone do you have? I'm at Spain :-)

**Comment by sebasgarcep** [comment]
I'm in Colombia but you may find me at any time with my unhealthy sleeping schedules :p

**Comment by piranna** [comment]
> I'm in Colombia but you may find me at any time with my unhealthy sleeping schedules :p

Me too, I have my cell phone all the time on my hand answering emails :-P

**Comment by wacii** [comment]
Ah, I didn't notice `JSON.stringify()` wraps strings in quotes. Guess it is definitely a breaking change.

I would add in the backwards compatibility check along with a deprecation message. It might help get the change into master faster, and the message would help people migrate.

**Comment by sorodrigo** [comment]
I'm having second thoughts about this...
> being it on purpose or an undercover bug
This made me think, and the reason its made like this IMHO is to give more flexibility to the users. For example, I have an aplication that needs to send form-data. This is easily achieved in the default effector by overriding the headers prop. If we stringify the body inside the effector, overriding will be imposible.

**Comment by piranna** [comment]
> This made me think, and the reason its made like this IMHO is to give more flexibility to the users. For example, I have an aplication that needs to send form-data. This is easily achieved in the default effector by overriding the headers prop. If we stringify the body inside the effector, overriding will be imposible.

Don't you think it would be unorthogonal send the data as `form-data` and receive it as json?

**Comment by sorodrigo** [comment]
I'm having second thoughts about this...
> being it on purpose or an undercover bug
This made me think, and the reason its made like this IMHO is to give more flexibility to the users. For example, I have an aplication that needs to send form-data. This is easily achieved in the default effector by overriding the headers prop. If we stringify the body inside the effector, overriding will be imposible.

**Comment by sorodrigo** [comment]
The effect tries reading responses as JSON, mainly because thats the most common response. And on error, it defaults to text giving the user the possibility of dealing with the response

**Comment by sorodrigo** [comment]
Sorry about closing, I'm on my mobile and its trolling me. That was accidental haha

**Comment by piranna** [comment]
> The effect tries reading responses as JSON, mainly because thats the most common response. And on error, it defaults to text giving the user the possibility of dealing with the response

I think if an API is returning JSON, then it also accept it (besides accepting other formats like `form-data`), so it makes sense to use the same serialization format both for sending and receiving.

**Comment by sorodrigo** [comment]
Anyway... I'm open on discussing this further and try reach a consensus, but i feel like we shouldn't sacrifice the flexibility just because of convenience. More thoughts? @piranna @wacii @sebasgarcep

**Comment by sorodrigo** [comment]
I think this library shouldn't depend on what an API should or shouldn't do. Not all API are restful. I think as a default we should try to include as many use cases as possible; leaving the more specific ones to custom effects. Sorry for being such a buzzkill

**Comment by piranna** [comment]
I have also seen that the `tryParseJSON()` function, if it doesn't receive an input it returns `null`. Being this now a valid JSON value, I think it would make more sense to return `undefined` instead, if not both `` (empty string, invalid JSON) and `null` (valid JSON) would return the same value... Also seems to be some kind of race condition or tests cache that make them fail at random after having added the `fetch()` mock.

**Comment by sebasgarcep** [comment]
I think restful APIs are common enough for @piranna's solution to make sense and to make life easier for the average user. And if you don't like the way we handle effects you can always override it with your own method, so it's not as if we are taking power away from the user.

**Comment by wacii** [comment]
> For example, I have an aplication that needs to send form-data. This is easily achieved in the default effector by overriding the headers prop. If we stringify the body inside the effector, overriding will be imposible.

Ah, I didn't think you could override the headers prop. You might be able to tell that I've never used the default effect reconciler before...

In that case, you might want to check `Content-Type` before stringifying the body.

**Comment by piranna** [comment]
In that case, you might want to check Content-Type before stringifying the
body.

Are you talking about doing the content-type check on the default effector,
as a backwards compatibility double-check?

**Comment by piranna** [comment]
Tests passing.

**Comment by wacii** [comment]
Thought about this some more, and I don't really want to include any backwards compatibility checks. Fetch isn't a great API, which is why HTTP clients are so popular. But it takes a lot of code to make something both flexible and convenient, and that's not something I want to do here.

But a convenience isn't worth breaking changes or the effort to avoid them, so I'd say either shelve this until a new major version, or release it as a separate effect reconciler.

If we didn't have to worry about breaking changes, I would go with this change. It is so easy to write your own effect reconciler, I think it is more important for the default to be easy to use and convenient than flexible.

**Comment by sorodrigo** [comment]
I agree, let's not introduce the breaking changes. However, the tests are a nice thing to have!

**Comment by piranna** [comment]
> But a convenience isn't worth breaking changes or the effort to avoid them, so I'd say either shelve this until a new major version, or release it as a separate effect reconciler.

Well... the effort is already done and pushed on this pull-request, so... :-P But I agree, I would just add a deprecation notice and don't touch it anymore, and think about doing a list of things needed to be added and deprecated for a new major release.


> I think it is more important for the default to be easy to use and convenient than flexible.

+1000

**Comment by sorodrigo** [comment]
Could you cherry-pick the tests and update them to the current behavior if needed (should be quite straightforward). And make them a new PR? It would be nice to include that now. 😄

**Comment by piranna** [comment]
> Could you cherry-pick the tests and update them to the current behavior if needed

What current behaviour? Needing users explicitly to use JSON.stringify()?

**Comment by sorodrigo** [comment]
Exactly

**Comment by piranna** [comment]
> Exactly

[Done](https://github.com/redux-offline/redux-offline/pull/43)

**Comment by piranna** [comment]
Any update on this? How we should proceed on that?

**Comment by sorodrigo** [comment]
We decided to shelve this, to avoid dealing with the breaking changes. So for now its not on the immediate roadmap.

**Comment by piranna** [comment]
> We decided to shelve this, to avoid dealing with the breaking changes. So for now its not on the immediate roadmap.

Ok, thanks to clarify it.

**Comment by piranna** [comment]
Instead of clossing this, can it be re-open and set a `next-major` label or similar thing so it can't be forgotten?

**Pull request closed without merging**
