### PR TITLE
redux-persist v5 compatibility

### PR DESCRIPTION
**Pull request by Anu2g**

### CODE REVIEW

**Comment by wacii** [comment]
Thanks for the PR. This is definitely something we will want to include in the next release. It has been brought up in PR #135, but this is a bit cleaner.

**Comment by gusgard** [comment]
@Anu2g Could you resolve the conflict? I would like to try version 5.

Thanks!

**Comment by sorodrigo** [comment]
@wacii what’s the status on this?

**Comment by wacii** [comment]
@sorodrigo This should be included. The new version of Redux Persist can dispatch a rehydrate event without a payload. So this just ignores those events, rather than throw an error when we try to access the nonexistent offline state.

**Comment by sorodrigo** [comment]
This is stupid, Github is forcing me to resolve the same issue twice. 😒

**Pull request merged**
