### PR TITLE
Prevent outdated connectivity info from updating the online status

### PR DESCRIPTION
**Pull request by birgernass**
Sometimes the DetectNetwork#init method (called in the constructor) updates the online status to 'unknown' after one of the event listeners already updated the online status with the correct reachability. This happens especially on iOS and prevents all queued actions from being fired.

### CODE REVIEW

**Comment by sorodrigo** [comment]
Hey! Thanks for bringing this up. I think a more elegant solution would be to await `this._init()` on the constructor. That would prevent init executing after the events the event listeners triggers.

**Comment by birgernass** [comment]
I don't think that we can await in the constructor. I'm also concerned that we would set the event listeners too late and that we would miss the first change and connectionChange events, resulting in the status being unknown again. But I like to be convinced of the contrary and I'm totally open to different solutions.

**Comment by sorodrigo** [comment]
I think to remember that the events trigger more than once, that's why we check if they trigger a change before dispatching. If this is true, I think awaiting in the constructor won't be that problematic. Maybe we could test if this works and if not continue with another solution.

**Comment by birgernass** [comment]
They do trigger more than once, but not necessarily on app start. They trigger once on startup. At least in my experience. After that, the network connectivity or the app state (foreground/background) have to change. But when they don't, the state sometimes remains 'unknown'. As I said, this doesn't happen every time, but often enough to be reproducible for me.

**Comment by sorodrigo** [comment]
I get your point, I think that a lot of people suffered this issue without noticing. Thanks for identifying it and providing a fix! 🎉

**Pull request merged**
