### PR TITLE
Peek with additional context parameter

### PR DESCRIPTION
**Pull request by Xyzor**
This PR is based on the #207 PR, with the requested changes.

### CODE REVIEW

**Comment by wacii** [comment]
Nifty. This looks good.

The docs need to be updated, but I'll do that when I work on the other queue methods.

**Comment by sorodrigo** [comment]
Hey so I was adding the context param to `enqueue` and `dequeue` and it felt weird to add `action` into context and at the same time as the second param. I changed the discussed API a little bit (trying to add some consistency), so now `peek` receives the action as a second param and the context with offline state as a third.

Also, `context.offline` state doesn't have the outbox because it's the rest of the state after extracting the outbox. Don't know if this will be confusing, but the outbox is the first param so don't know if it matters.

Thoughts??

@wacii @Xyzor

**Review by wacii — APPROVED** [review]
Looks good. Having a consistent function signature across the queue methods is a plus.

I would prefer having context as minimal as possible, so maybe adding the rest of offline state directly onto context, but only documenting the `online` property. But I don't have a good justification for that, so this is fine.

**Comment by Xyzor** [comment]
Hy!

I don't see a better solution without causing a breaking change.

**Comment by wacii** [comment]
Oh right. I always forget about the types...

**Comment by sorodrigo** [comment]
Gotta catch 'em all

hahaha ok so this looks good to go, merging!

**Pull request merged**
